### PR TITLE
Make syntax more clear and add 💀

### PR DESCRIPTION
**Pull request by nonetrix**

### CODE REVIEW

**Comment by nonetrix** [comment]
I am already working on selling a keyboard that has all these stay tuned

**Comment by nonetrix** [comment]
And no I haven't checked if GCC or clang supports unicode in defines nor do I care since no one asked 💀

**Comment by nonetrix** [comment]
> I am already working on selling a keyboard that has all these stay tuned

Wait no one asked 🤨🤨🤨💀🤨💀🤨💀🤨

**Comment by zoooomie** [comment]
Pls put that in a separate file, I have no idea which compilers support that

**Comment by N-R-K** [comment]
> emojies

cringe

**Comment by ghost** [comment]
basedmojis for zoomerlib

**Comment by nonetrix** [comment]
too lazy

**Pull request closed without merging**
